/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mikedhanny
 */
public class calculator extends javax.swing.JFrame {
 String angka="";
    int jumlah,angka1,angka2;
    int pilih;
    /**
     * Creates new form calculator
     */
    public calculator() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HASIL = new javax.swing.JTextField();
        bilangan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ButtonA = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        ButtonF = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonCE = new javax.swing.JButton();
        ButtonCULANG = new javax.swing.JButton();
        Buttonkali = new javax.swing.JButton();
        Buttonbagi = new javax.swing.JButton();
        Buttontambah = new javax.swing.JButton();
        ButtonDEC = new javax.swing.JButton();
        ButtonOCT = new javax.swing.JButton();
        ButtonBIN = new javax.swing.JButton();
        Buttonmin = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Programmer");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("HEX");

        HASIL.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        HASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HASILActionPerformed(evt);
            }
        });

        bilangan.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        bilangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilanganActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("HASIL");

        ButtonA.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonA.setText("A");
        ButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAActionPerformed(evt);
            }
        });

        ButtonB.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonB.setText("B");
        ButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBActionPerformed(evt);
            }
        });

        ButtonD.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonD.setText("D");
        ButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDActionPerformed(evt);
            }
        });

        ButtonC.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonC.setText("C");
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        ButtonE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonE.setText("E");
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });

        ButtonF.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonF.setText("F");
        ButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button9.setText("9");
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        ButtonCE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonCE.setText("CE");
        ButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCEActionPerformed(evt);
            }
        });

        ButtonCULANG.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonCULANG.setText("C");
        ButtonCULANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCULANGActionPerformed(evt);
            }
        });

        Buttonkali.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Buttonkali.setText("X");
        Buttonkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonkaliActionPerformed(evt);
            }
        });

        Buttonbagi.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Buttonbagi.setText("/");
        Buttonbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonbagiActionPerformed(evt);
            }
        });

        Buttontambah.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Buttontambah.setText("+");
        Buttontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontambahActionPerformed(evt);
            }
        });

        ButtonDEC.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonDEC.setText("DEC");
        ButtonDEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDECActionPerformed(evt);
            }
        });

        ButtonOCT.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonOCT.setText("OCT");
        ButtonOCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOCTActionPerformed(evt);
            }
        });

        ButtonBIN.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        ButtonBIN.setText("BIN");
        ButtonBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBINActionPerformed(evt);
            }
        });

        Buttonmin.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        Buttonmin.setText("-");
        Buttonmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonminActionPerformed(evt);
            }
        });

        samadengan.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button1)
                                    .addComponent(Button4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(Button7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonOCT)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Button9)
                                                .addGap(18, 18, 18)
                                                .addComponent(ButtonCE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ButtonCULANG))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Button6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Buttonmin))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(Button3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(Buttonkali)))
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Buttontambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Buttonbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(samadengan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(ButtonDEC))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonBIN)))))
                        .addGap(515, 515, 515))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButtonC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButtonD)))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Button5)
                                    .addComponent(Button2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bilangan, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(HASIL)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonA)
                    .addComponent(ButtonB)
                    .addComponent(Button7)
                    .addComponent(Button9)
                    .addComponent(ButtonCE)
                    .addComponent(ButtonCULANG)
                    .addComponent(ButtonDEC)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonD)
                    .addComponent(ButtonC)
                    .addComponent(Button4)
                    .addComponent(Button5)
                    .addComponent(Button6)
                    .addComponent(Buttonbagi)
                    .addComponent(ButtonOCT)
                    .addComponent(Buttonmin))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonE)
                    .addComponent(ButtonF)
                    .addComponent(Button1)
                    .addComponent(Button2)
                    .addComponent(Button3)
                    .addComponent(Buttonkali)
                    .addComponent(Buttontambah)
                    .addComponent(ButtonBIN))
                .addComponent(samadengan)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilanganActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bilanganActionPerformed

    private void ButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAActionPerformed
        // TODO add your handling code here:
        angka +="11"; 
        bilangan.setText(angka);
        
    }//GEN-LAST:event_ButtonAActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
         angka +="1"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button1ActionPerformed

    private void ButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBActionPerformed
        // TODO add your handling code here:
         angka +="12"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_ButtonBActionPerformed

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
        // TODO add your handling code here:
         angka +="13"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_ButtonCActionPerformed

    private void ButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDActionPerformed
        // TODO add your handling code here:
         angka +="14"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_ButtonDActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
        // TODO add your handling code here:
         angka +="15"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_ButtonEActionPerformed

    private void ButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFActionPerformed
        // TODO add your handling code here:
         angka +="16"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_ButtonFActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
         angka +="7"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
         angka +="8"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
         angka +="9"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
         angka +="4"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
         angka +="5"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
         angka +="6"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
         angka +="2"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
         angka +="3"; 
        bilangan.setText(angka);
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCEActionPerformed
        // TODO add your handling code here:
         bilangan.setText("");
         angka1=0;
         angka2=0;
         jumlah=0;
         angka="";
         HASIL.setText("");
    }//GEN-LAST:event_ButtonCEActionPerformed

    private void ButtonCULANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCULANGActionPerformed
        // TODO add your handling code here:
         bilangan.setText("");
         angka1=0;
         angka2=0;
         jumlah=0;
         angka="";
         HASIL.setText("");
    }//GEN-LAST:event_ButtonCULANGActionPerformed

    private void ButtonminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonminActionPerformed
        // TODO add your handling code here:
          angka1=Integer.parseInt(angka);
         bilangan.setText(String.valueOf(" - "));
         angka="";
         pilih=2;
    }//GEN-LAST:event_ButtonminActionPerformed

    private void ButtonbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonbagiActionPerformed
        // TODO add your handling code here:
         angka1=Integer.parseInt(angka);
         bilangan.setText(String.valueOf(" / "));
         angka="";
         pilih=4;
    }//GEN-LAST:event_ButtonbagiActionPerformed

    private void ButtonkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonkaliActionPerformed
        // TODO add your handling code here:
      angka1=Integer.parseInt(angka);
         bilangan.setText(String.valueOf(" X "));
         angka="";
         pilih=3;
    }//GEN-LAST:event_ButtonkaliActionPerformed

    private void ButtontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontambahActionPerformed
        // TODO add your handling code here:
         angka1=Integer.parseInt(angka);
         bilangan.setText(String.valueOf(" + "));
         angka="";
         pilih=1;
        
    }//GEN-LAST:event_ButtontambahActionPerformed

    private void ButtonDECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDECActionPerformed
        // TODO add your handling code here:
          String oct =bilangan.getText();
        int outdesa=Integer.parseInt(oct,8);
      
        HASIL.setText(Integer.toUnsignedString(outdesa));
    }//GEN-LAST:event_ButtonDECActionPerformed

    private void ButtonOCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOCTActionPerformed
        // TODO add your handling code here:
        String oct =bilangan.getText();
        int outdes=Integer.parseInt(oct,16);
        String hasildes=Integer.toUnsignedString(outdes);
        int hasiloctal=Integer.parseInt(hasildes);
        HASIL.setText(Integer.toOctalString(hasiloctal));
    }//GEN-LAST:event_ButtonOCTActionPerformed

    private void ButtonBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBINActionPerformed
        // TODO add your handling code here:
  String hexa= bilangan.getText();
  int autdes2=Integer.parseInt(hexa,16);
 String hasildes=Integer.toUnsignedString(autdes2);
 int hasilbiner=Integer.parseInt(hasildes);
HASIL.setText(Integer.toBinaryString(hasilbiner));
          
    }//GEN-LAST:event_ButtonBINActionPerformed

    private void HASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HASILActionPerformed
        // TODO add your handling code here:
       
    
        
                                              
    }//GEN-LAST:event_HASILActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
          switch(pilih){
        case 1:
            angka2 =Integer.parseInt(angka);
            jumlah = angka1+angka2;
            angka = Integer.toString(jumlah);  
            bilangan.setText(angka);
            break;
        case 2:
            angka2 =Integer.parseInt(angka);
            jumlah = angka1 - angka2;
            angka= Integer.toString(jumlah);
             bilangan.setText(angka);
            break;
        case 3:
          angka2 =Integer.parseInt(angka);
            jumlah = angka1 * angka2;
            angka= Integer.toString(jumlah);
             bilangan.setText(angka);
            break;
        case 4:
            angka2 =Integer.parseInt(angka);
            jumlah = angka1 / angka2;
            angka= Integer.toString(jumlah);
             bilangan.setText(angka);
            break;    
          
          }
    }//GEN-LAST:event_samadenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonBIN;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonCE;
    private javax.swing.JButton ButtonCULANG;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonDEC;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonF;
    private javax.swing.JButton ButtonOCT;
    private javax.swing.JButton Buttonbagi;
    private javax.swing.JButton Buttonkali;
    private javax.swing.JButton Buttonmin;
    private javax.swing.JButton Buttontambah;
    private javax.swing.JTextField HASIL;
    private javax.swing.JTextField bilangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton samadengan;
    // End of variables declaration//GEN-END:variables
}
